/**
 * The web host: the same client, served to a browser tab.
 *
 * `MUDENGINE_WEB=1` selects it (`src/main/index.ts`). Sockets, files, the
 * realm database and the automation arbiter stay in main, in Node, exactly as
 * they are on the desktop — `client.ts` does not know which host it has. What
 * this module does is carry `IpcApi` over a WebSocket instead of `ipcMain`,
 * and answer the desktop's duties honestly:
 *
 * | duty | here |
 * |---|---|
 * | transport | `RpcRequest` in, `RpcOutbound` out, one socket per tab |
 * | windows | none: `windows` is null, and every tab draws the one rail |
 * | reveal, picker, clipboard | refused; the window answers each its own way |
 * | GPU | null: nothing here composites, and a guess would be the alarming kind |
 * | lifecycle | listen on `MUDENGINE_PORT`, end on the signal the client already handles |
 *
 * **Every tab is the whole client.** The desktop's pop-out model is a rail
 * per window with characters owned by one of them; a browser tab has no
 * second window to pop anything into, so `mainWindowId()` names one rail
 * (`WEB_RAIL`) and every tab is a view of it. Attachment is still per tab —
 * the registry routes the byte stream only to tabs showing a character — so
 * two tabs on two characters cost what two windows would.
 *
 * The gate is `web/access.ts` and `web/server.ts`: one password, resolved
 * the way the noVNC image resolved it, a session cookie once given, and the
 * socket refused before any channel is served. Cleartext unless something
 * terminates TLS in front, and the banner says so every start.
 */
import os from 'node:os';
import path from 'node:path';

import { asRpcRequest, type RpcOutbound } from '../../shared/rpc';
import { errorMessage } from '../../shared/values';
import { platformUserData } from '../app/home';
import { t } from '../app/i18n';
import { tuning } from '../app/tuning';
import type { Caller, ClientHooks, Handler, Host, Layout, Transport } from './Host';
import { AccessTokens, resolveAccessPassword, type AccessPassword } from './web/access';
import { createWebServer, type WebServer } from './web/server';
import type { WebSocketConnection } from './web/sockets';

/** The one rail every tab draws. Tabs are numbered from the next id up. */
export const WEB_RAIL = 1;

/** What a client that is not behind a proxy listens on: this machine only. */
const DEFAULT_PORT = 8080;
const DEFAULT_BIND = '127.0.0.1';

interface Tab {
  readonly id: number;
  readonly connection: WebSocketConnection;
  /** Answered the last ping; cleared when the next one goes out. */
  alive: boolean;
}

/** `MUDENGINE_PORT`, or the default; `0` asks the system for a free one. */
function portFrom(env: NodeJS.ProcessEnv): number {
  const raw = (env['MUDENGINE_PORT'] ?? '').trim();
  if (raw.length === 0) return DEFAULT_PORT;
  const port = Number(raw);
  if (!Number.isInteger(port) || port < 0 || port > 65535) {
    throw new Error(`MUDENGINE_PORT is "${raw}", which is not a port.`);
  }
  return port;
}

/**
 * The addresses a browser on another machine could use, when bound to all of
 * them. `::` is every address of both families, and an IPv6 one is written
 * the way a URL wants it.
 */
function reachableAddresses(bind: string): string[] {
  if (bind !== '0.0.0.0' && bind !== '::') return [bind];
  const found: string[] = [];
  for (const entries of Object.values(os.networkInterfaces())) {
    for (const entry of entries ?? []) {
      if (entry.internal) continue;
      if (entry.family === 'IPv4') found.push(entry.address);
      else if (bind === '::' && entry.family === 'IPv6' && !entry.address.startsWith('fe80')) {
        found.push(`[${entry.address}]`);
      }
    }
  }
  return found;
}

function banner(
  bound: { port: number; host: string },
  access: AccessPassword,
  home: string,
  trustProxy: boolean
): string {
  const rule = '  ────────────────────────────────────────────────────────────────';
  const lines = [
    '',
    rule,
    '   mudengine is serving the client over HTTP.',
    '',
    `   Open:  http://localhost:${bound.port}/`
  ];
  for (const address of reachableAddresses(bound.host)) {
    if (address !== '127.0.0.1') lines.push(`          http://${address}:${bound.port}/`);
  }
  lines.push('', '   Sign in with the password');
  switch (access.source) {
    case 'generated':
      lines.push(
        `     ${access.password}`,
        '',
        '   That password was generated by this first start and saved to',
        `   ${access.file}. It is printed here once and never again.`,
        '   Set MUDENGINE_PASSWORD to choose your own instead.'
      );
      break;
    case 'saved':
      lines.push(
        '     generated on the first start.',
        '',
        `   It is in ${access.file}. Delete that file to have a new one`,
        '   generated, or set MUDENGINE_PASSWORD.'
      );
      break;
    case 'env':
      lines.push('     you set in MUDENGINE_PASSWORD.');
      break;
  }
  lines.push(
    '',
    `   Files are under ${home}.`,
    '',
    '   The connection is NOT encrypted. On anything but a machine you',
    '   are sitting at, put a TLS-terminating proxy in front of this',
    '   port -- the password and the session cookie travel in the clear.'
  );
  if (trustProxy) {
    lines.push(
      '',
      '   MUDENGINE_TRUST_PROXY is set: a request whose X-Forwarded-Proto',
      '   says https is treated as encrypted. Only a proxy you control',
      '   may sit in front of this port.'
    );
  }
  lines.push(rule, '');
  if (bound.host === DEFAULT_BIND) {
    lines.splice(
      lines.length - 2,
      0,
      '',
      '   Listening on this machine only. Set MUDENGINE_BIND=0.0.0.0 to',
      '   reach it from another.'
    );
  }
  return lines.join('\n');
}

export function createWebHost(layout: Layout): Host {
  const handlers = new Map<string, Handler>();
  const listeners = new Map<string, Handler>();
  const tabs = new Map<number, Tab>();
  let nextId = WEB_RAIL + 1;
  let server: WebServer | null = null;
  let sweep: NodeJS.Timeout | null = null;
  let closing = false;

  const transport: Transport = {
    handle: (channel, handler) => handlers.set(channel, handler),
    on: (channel, listener) => listeners.set(channel, listener)
  };

  const say = (line: string): void => console.log(line);

  const push = (tab: Tab, message: RpcOutbound): void => {
    if (!tab.connection.open) return;
    let text: string;
    try {
      text = JSON.stringify(message);
    } catch (error) {
      // A payload JSON cannot carry is a defect in the thing that pushed it,
      // and one worth naming: the tab would otherwise wait for a reply that
      // never comes.
      console.error(`web: could not serialise a message on ${message.k}: ${errorMessage(error)}`);
      if (message.k === 'reply') {
        tab.connection.send(JSON.stringify({ k: 'reply', id: message.id, e: errorMessage(error) }));
      }
      return;
    }
    tab.connection.send(text);
  };

  /** One message from a tab, parsed and dispatched. */
  const dispatch = (tab: Tab, caller: Caller, text: string): void => {
    let parsed: unknown;
    try {
      parsed = JSON.parse(text);
    } catch {
      parsed = null;
    }
    const request = asRpcRequest(parsed);
    // Not our bridge. A tab that speaks something else is not answered in
    // kind; it is closed with the code that says the message was refused.
    if (request === null) {
      tab.connection.close(1008, 'malformed message');
      return;
    }

    if (request.k === 'send') {
      const listener = listeners.get(request.c);
      if (!listener) {
        say(`web: nothing listens on ${request.c}.`);
        return;
      }
      try {
        listener(caller, ...request.a);
      } catch (error) {
        // `ipcMain.on` would have raised this as an uncaught exception, which
        // `guardTheProcess` reports; here it is reported directly so a defect
        // in one handler costs one call and not the tab.
        console.error(`web: ${request.c} threw: ${errorMessage(error)}`);
      }
      return;
    }

    const handler = handlers.get(request.c);
    if (!handler) {
      push(tab, { k: 'reply', id: request.id, e: t('web.rpc.noHandler', { channel: request.c }) });
      return;
    }
    Promise.resolve()
      .then(() => handler(caller, ...request.a))
      .then(
        (result) => push(tab, { k: 'reply', id: request.id, r: result }),
        (error: unknown) => push(tab, { k: 'reply', id: request.id, e: errorMessage(error) })
      );
  };

  const attach = (hooks: ClientHooks, connection: WebSocketConnection, remote: string): void => {
    const id = nextId;
    nextId += 1;
    const tab: Tab = { id, connection, alive: true };
    tabs.set(id, tab);
    const caller: Caller = {
      windowId: id,
      send: (channel, payload) => push(tab, { k: 'push', c: channel, p: payload })
    };
    hooks.windows.add({
      id,
      isDestroyed: () => !connection.open,
      send: (channel, payload) => push(tab, { k: 'push', c: channel, p: payload })
    });
    connection.onPong = () => {
      tab.alive = true;
    };
    connection.onMessage = (text) => dispatch(tab, caller, text);
    connection.onClose = (code, reason) => {
      tabs.delete(id);
      hooks.windows.remove(id);
      if (!closing) {
        say(`web: tab ${id} from ${remote} closed (${code}${reason ? ` ${reason}` : ''}).`);
      }
    };
    say(`web: tab ${id} connected from ${remote}.`);
  };

  /**
   * Find the tabs that have gone without saying so.
   *
   * A tab that did not answer the last ping is closed; every other one is
   * pinged again. Rescheduled from the file each time rather than set once,
   * so an edit to `pingIntervalMs` reaches the next tick.
   */
  const scheduleSweep = (): void => {
    sweep = setTimeout(() => {
      for (const tab of tabs.values()) {
        if (!tab.alive) {
          tab.connection.close(1001, 'no answer to ping');
          continue;
        }
        tab.alive = false;
        tab.connection.ping();
      }
      scheduleSweep();
    }, tuning().web.pingIntervalMs);
  };

  return {
    kind: 'web',
    packaged: false,
    defaultHome: platformUserData(process.platform, process.env, os.homedir(), 'mudengine'),
    resourcesPath: null,
    resourceCandidates: () => [layout.resources, path.join(process.cwd(), 'resources')],
    runtime: `Node ${process.versions.node}, served over HTTP`,
    transport,

    ready: () => Promise.resolve(),
    // The port is the lock: a second client on the same one fails to listen
    // and says so, below.
    claimInstance: () => true,

    open: (hooks) => {
      let access: AccessPassword;
      try {
        access = resolveAccessPassword(process.env, hooks.home.root);
      } catch (error) {
        hooks.abort(`web: could not resolve the access password: ${errorMessage(error)}`);
        return;
      }
      const tokens = new AccessTokens();
      hooks.workspace()?.open(WEB_RAIL);

      let port: number;
      try {
        port = portFrom(process.env);
      } catch (error) {
        hooks.abort(`web: ${errorMessage(error)}`);
        return;
      }
      const bind = (process.env['MUDENGINE_BIND'] ?? '').trim() || DEFAULT_BIND;
      /*
       * Whether `X-Forwarded-Proto` is believed. It arrives in the request,
       * so believing it by default lets a hop that is not TLS to the browser
       * suppress the cleartext warning and mark the cookie `Secure`. Off
       * unless whoever runs the client says a proxy of theirs is in front.
       */
      const trustProxy = (process.env['MUDENGINE_TRUST_PROXY'] ?? '').trim() === '1';

      server = createWebServer({
        rendererDir: layout.rendererDir,
        password: access.password,
        tokens,
        trustProxy,
        onSocket: (connection, remote) => attach(hooks, connection, remote),
        log: say
      });
      server.listen(port, bind).then(
        (bound) => {
          say(banner(bound, access, hooks.home.root, trustProxy));
          scheduleSweep();
        },
        (error: unknown) => hooks.abort(`web: could not listen: ${errorMessage(error)}`)
      );
    },

    windows: null,
    mainWindowId: () => WEB_RAIL,

    gpu: () => null,
    reveal: () => Promise.resolve(false),
    /*
     * Never asked — a tab's bridge draws its own picker over `browseHome` —
     * and said so if it ever is, because `null` alone reads as "dismissed"
     * to the window that asked.
     */
    chooseFile: () => {
      console.warn('web: asked for a native file picker; there is none here.');
      return Promise.resolve(null);
    },
    clipboard: null,

    /*
     * Unreachable: nothing in web mode asks to quit. A tab closing closes a
     * view and disconnects nobody, and the process ends on a signal, which
     * runs the same teardown without asking — whoever sent `docker stop` has
     * already decided. Kept honest rather than omitted: if a way to quit from
     * a tab is ever added, this is the answer that refuses by default, and
     * it says so.
     */
    askAboutQuitting: () => {
      console.warn('web: asked to confirm a quit with nowhere to ask; staying.');
      return 'stay';
    },

    close: () => {
      closing = true;
      if (sweep !== null) clearTimeout(sweep);
      sweep = null;
      for (const tab of tabs.values()) tab.connection.close(1001, 'the client is shutting down');
      tabs.clear();
      server?.close();
      server = null;
    },
    exit: (code) => process.exit(code)
  };
}
